In [47]:
import pandas as pd

df = pd.read_csv('movie_data.csv', encoding='utf-8')

df

review  sentiment
0      In 1974, the teenager Martha Moxley (Maggie Gr...          1
1      OK... so... I really like Kris Kristofferson a...          0
2      ***SPOILER*** Do not read this, if you think a...          0
3      hi for all the people who have seen this wonde...          1
4      I recently bought the DVD, forgetting just how...          0
5      Leave it to Braik to put on a good show. Final...          1
6      Nathan Detroit (Frank Sinatra) is the manager ...          1
7      To understand "Crash Course" in the right cont...          1
8      I've been impressed with Chavez's stance again...          1
9      This movie is directed by Renny Harlin the fin...          1
10     I once lived in the u.p and let me tell you wh...          0
11     Hidden Frontier is notable for being the longe...          1
12     It's a while ago, that I have seen Sleuth (197...          0
13     What is it about the French? First, they (appa...          0
14     This very strange movie is unlike anything mad...          1
15     I saw this movie on the strength of the single...          0
16     There are some great philosophical questions. ...          0
17     I was cast as the Surfer Dude in the beach sce...          1
18     I had high hopes for this one until they chang...          0
19     Set in and near a poor working class town in t...          1
20     Opulent sets and sumptuous costumes well photo...          0
21     i saw the film and i got screwed, because the ...          0
22     I'm getting a little tired of people misusing ...          0
23     How offensive! Those who liked this movie have...          0
24     What else can you say about this movie,except ...          0
25     Certain aspects of Punishment Park are less th...          1
26     First of all, I'd like to tell you that I'm in...          0
27     You should not take what I am about to say lig...          1
28     I love the Jurassic Park movies, they are thre...          0
29     The first series of Lost kicked off with a ban...          1
...                                                  ...        ...
49970  Tom Fontana's unforgettable "Oz" is hands down...          1
49971  Last weekend I bought this 'zombie movie' from...          0
49972  I watched the first few moments on TCM a few y...          1
49973  I saw this movie for the first time in 1988 wh...          1
49974  Al Pacino? Kim Basinger? Tea Leoni? Ryan O'Nea...          0
49975  Stanwyck at her villainous best, Robinson her ...          1
49976  An allegation of aggravated sexual assault alo...          0
49977  i thought this movie was wonderfully plotted i...          1
49978  Just like most people, I couldn't wait to see ...          0
49979  Dark comedy? Gallows humor? How does one make ...          1
49980  ****Probably will contain spoilers****<br /><b...          0
49981  I must be that one guy in America that didn't ...          0
49982  THE PLOT: A trucker (Kristofferson) battles a ...          0
49983  The Ladies Man is laugh out loud funny, with a...          1
49984  Well, the artyfartyrati of Cannes may have lik...          0
49985  The director was probably still in his early l...          0
49986  You know when you're on the bus and someone de...          0
49987  Five minutes into this movie you realize that ...          0
49988  ...If you've been laughing too much for a long...          0
49989  I love dissing this movie. My peers always try...          0
49990  OK. I think the TV show is kind of cute and it...          0
49991  Big disappointment. CLASH BY NIGHT is much to ...          0
49992  Cassidy(Kacia Brady)puts a gun in her mouth bl...          0
49993  With rapid intercutting of scenes of insane pe...          1
49994  When "Girlfight" came out, the reviews praised...          1
49995  OK, lets start with the best. the building. al...          0
49996  The British 'heritage film' industry is out of...          0
49997  I don't even know where to begi

In [3]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
docs = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining, the weather is sweet, and one and one is two'
                ])
bag = count.fit_transform(docs)

print(count.vocabulary_)
print(bag.toarray())

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}
[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [10]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
np.set_printoptions(precision=2)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())



[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


In [64]:
df.loc[0,'review'][-50:]

'is seven.<br /><br />Title (Brazil): Not Available'

In [22]:
import re

def preprocessor(text):
    
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = (re.sub('[\W]+', ' ', text.lower()) + ' '.join(emoticons).replace('-', ''))
    
    return text

In [29]:
text = df.loc[0,'review']
#print(text)
#print(' ')
print(preprocessor(text))

in 1974 the teenager martha moxley maggie grace moves to the high class area of belle haven greenwich connecticut on the mischief night eve of halloween she was murdered in the backyard of her house and her murder remained unsolved twenty two years later the writer mark fuhrman christopher meloni who is a former la detective that has fallen in disgrace for perjury in o j simpson trial and moved to idaho decides to investigate the case with his partner stephen weeks andrew mitchell with the purpose of writing a book the locals squirm and do not welcome them but with the support of the retired detective steve carroll robert forster that was in charge of the investigation in the 70 s they discover the criminal and a net of power and money to cover the murder murder in greenwich is a good tv movie with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a kennedy the powerful and rich family used their influence to cover the murd

In [30]:
df['review'] = df['review'].apply(preprocessor)

In [54]:
def tokenizer(text):
    return text.split()

tokenizer('runners like running and tus the run')

['runners', 'like', 'running', 'and', 'tus', 'the', 'run']

In [37]:
from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

tokenizer_porter('runners like running and tus the run')

['runner', 'like', 'run', 'and', 'tu', 'the', 'run']

In [41]:

text = 'runners like running and tus the run'
text.split()

porter = PorterStemmer()
porter.stem('running')

'run'

In [43]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\y-kobayashi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [46]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

[w for w in tokenizer_porter('runners like running and tus the run') if w not in stop]

['runner', 'like', 'run', 'tu', 'run']

In [55]:
# from sklearn.model_selection import GridSearchCV
# from sklearn.pipeline import Pipeline
# from sklearn.linear_model import LogisticRegression
# from sklearn.feature_extraction.text import TfidfVectorizer

# X_train = df.loc[:25000, 'review'].values
# y_train = df.loc[:25000, 'sentiment'].values
# X_test = df.loc[25000:, 'review'].values
# y_test = df.loc[25000:, 'sentiment'].values

# tfidf = TfidfVectorizer(strip_accents=None, lowercase=False, preprocessor=None)

# param_grid = [{'vect__ngram_range': [(1, 1)],
#                'vect__stop_words': [stop, None],
#                'vect__tokenizer': [tokenizer, tokenizer_porter],
#                'clf__penalty': ['l1', 'l2'],
#                'clf__C': [1.0, 10.0, 100.0]},
#               {'vect__ngram_range': [(1, 1)],
#                'vect__stop_words': [stop, None],
#                'vect__tokenizer': [tokenizer, tokenizer_porter],
#                'vect__use_idf':[False],
#                'vect__norm':[None],
#                'clf__penalty': ['l1', 'l2'],
#                'clf__C': [1.0, 10.0, 100.0]},
#               ]

# lr_tfidf = Pipeline([('vect', tfidf), ('clf', LogisticRegression(random_state=0))])
# gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid, scoring='accuracy', cv=5, verbose=1, n_jobs=1)
# gs_lr_tfidf.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


KeyboardInterrupt: 

In [60]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

X_train = df.loc[:25000, 'review'].values
y_train = df.loc[:25000, 'sentiment'].values
X_test = df.loc[25000:, 'review'].values
y_test = df.loc[25000:, 'sentiment'].values

tfidf = TfidfVectorizer(strip_accents=None, lowercase=False, preprocessor=None, ngram_range=(1,1), stop_words=stop, tokenizer=tokenizer_porter)

param_grid = [{'vect__ngram_range': [(1, 1)],
               'vect__stop_words': [stop, None],
               'vect__tokenizer': [tokenizer, tokenizer_porter],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              {'vect__ngram_range': [(1, 1)],
               'vect__stop_words': [stop, None],
               'vect__tokenizer': [tokenizer, tokenizer_porter],
               'vect__use_idf':[False],
               'vect__norm':[None],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              ]

lr_tfidf = Pipeline([('vect', tfidf), ('clf', LogisticRegression(random_state=0))])
lr_tfidf.fit(X_train, y_train)

# y_pred = lr_tfidf.predict(X_train)
print('Train Accuracy: %.3f' % lr_tfidf.score(X_train, y_train))
print('Test Accuracy: %.3f' % lr_tfidf.score(X_test, y_test))

Train Accuracy: 0.936
Test Accuracy: 0.881
