In [8]:
import tensorflow as tf

g = tf.Graph()

with g.as_default():
    
    x = tf.placeholder(dtype=tf.float32, shape=(None), name='x')
    w = tf.Variable(2.0, name='weight')
    b = tf.Variable(0.7, name='bias')
    z = w * x + b
    init = tf.global_variables_initializer()
    
with tf.Session(graph=g) as session:
    
    session.run(init)
    for t in [1.0, 0.6, -1.8]:
        print('x=%4.1f --> z=%4.1f' % (t, session.run(z, feed_dict={x:t})))
    
    #print(session.run(z, feed_dict={x:[1.0, 2.0, 3.0]}))


x= 1.0 --> z= 2.7
x= 0.6 --> z= 1.9
x=-1.8 --> z=-2.9


In [21]:
import tensorflow as tf
import numpy as np

g = tf.Graph()

with g.as_default():
    
    x = tf.placeholder(dtype=tf.float32, shape=(None, 2, 3), name='input_x')
    x2 = tf.reshape(x, shape=(-1, 6), name='x2')
    print(x)
    print(x2)
    xsum = tf.reduce_sum(x2, axis=0, name='col_sum')
    xmean = tf.reduce_mean(x2, axis=0, name='col_mean')
    print(xsum)
    print(xmean)
    print('\n')
    
with tf.Session(graph=g) as session:
    
    x_array = np.arange(18).reshape(3,2,3)
    print('input shape: ', x_array.shape)
    print('Reshape:\n', session.run(x2, feed_dict={x:x_array}))
    print('Column Sums:\n', session.run(xsum, feed_dict={x:x_array}))
    print('Column Means:\n', session.run(xmean, feed_dict={x:x_array}))
    

Tensor("input_x:0", shape=(?, 2, 3), dtype=float32)
Tensor("x2:0", shape=(?, 6), dtype=float32)
Tensor("col_sum:0", shape=(6,), dtype=float32)
Tensor("col_mean:0", shape=(6,), dtype=float32)


input shape:  (3, 2, 3)
Reshape:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]]
Column Sums:
 [18. 21. 24. 27. 30. 33.]
Column Means:
 [ 6.  7.  8.  9. 10. 11.]


In [15]:
np.arange(18).reshape(3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])